config/routes.rb
Microsites2::Application.routes.draw do

  root :to => 'welcome#home'

  # then it just disappears...
  # get "/ru/reports/view/Explanation_Of_Symbolic_Links" => redirect { |params, request| "http://piousbox.com/en/users/show/piousbox" }
  
  scope "/:locale", :constraints => { :locale => /en|ru|pt/ } do

    root :to => 'welcome#home'
    get 'about', :to => 'welcome#about', :as => :about
    post 'set_city', :to => 'welcome#set_city', :as => :set_city
    get 'privacy', :to => 'welcome#privacy', :as => :privacy
    get 'contact', :to => 'welcome#contact', :as => :contact
    
    devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :registrations => 'users/registrations'
    }

    get "sites/:domainname.html/newsitems/page/:newsitems_page" => redirect { |params, request|
      "/#{params[:locale]}/sites/#{params[:domainname]}/newsitems/page/#{params[:newsitems_page]}" 
    }, :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    get "sites/:domainname.html", :to => "sites#show", :as => :site,   :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    get 'sites/:domainname/tags', :to => 'tags#index', :as => :tags,   :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    get 'sites/:domainname/tags/page/:tags_page', :to => 'tags#index', :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    scope 'sites/:domainname',                         :as => :sites,  :constraints => { :domainname => /.*/, :format => /xml|html|json/ } do
      get 'features', :to => 'sites#features', :as => :features
      get 'features/page/:features_page', :to => 'sites#features'
      get 'newsitems/page/:newsitems_page', :to => 'sites#show'
      get 'newspage/:newsitems_page' => redirect { |p,r| "/#{p[:locale]}/sites/#{p[:domainname]}/newsitems/page/#{p[:newsitems_page]}" }

      get 'reports', :to => 'reports#index', :as => :reports
      get 'reports/page/:reports_page', :to => 'reports#index'

      get 'galleries', :to => 'galleries#index', :as => :galleries
      get 'galleries/page/:galleries_page', :to => 'galleries#index'

      get 'sitemap' => redirect { |params, request| "http://#{request.domain}/en/sitemap.xml" }
    end

    get 'reports', :to => 'reports#index', :as => :reports
    get 'reports/page/:reports_page', :to => 'reports#index' # @deprecated, but keep it for Google
    get 'reports/view/:name_seo', :to => 'reports#show', :as => :report
    get 'reports/show/:name_seo', :to => 'reports#show' # @deprecated, I think I'll go with `view` word.
    put 'reports/:id', :to => 'reports#update', :as => :update_report
    get 'reports/:id/edit', :to => 'reports#edit', :as => :edit_report
    get 'reports/new', :to => 'reports#new', :as => :new_report
    post 'reports', :to => 'reports#create'
    resources :reports

    get 'galleries', :to => 'galleries#index', :as => :galleries
    get 'galleries/page/:galleries_page', :to => 'galleries#index' # @deprecated, keep it for Google
    get 'galleries/new', :to => 'galleries#new', :as => :new_gallery
    # @deprecated, instead of `show` there should be `style`
    get 'galleries/show/:galleryname/:photo_idx', :to => 'galleries#show', :as => :gallery, :constraints => { :photo_idx => /.*/ }
    get 'galleries/view/:galleryname' => redirect {|p,r| "/#{p[:locale]}/galleries/show/#{p[:galleryname]}/0" }
    # @deprecated, instead of `show` there should be `style`
    get 'galleries/j_show/:id', :to => 'galleries#j_show', :as => :j_gallery, :defaults => { :format => :json }
    get 'galleries/:style/:galleryname', :to => 'galleries#show', :as => :gallery_show_style, :constraints => { :style => /show_long|show_mini|show/ }
    get 'galleries/:id/edit', :to => 'galleries#edit', :as => :edit_gallery
    post 'galleries/:id', :to => 'galleries#update', :as => :update_gallery
    post 'galleries', :to => 'galleries#create'
    get 'galleries/:galleryname/multiadd', :to => 'photos#multinew', :as => :gallery_multiadd_photos
    post 'galleries/:galleryname/multiadd', :to => 'photos#j_create', :as => :gallery_multiadd_photos, :defaults => { :format => :json }
    get 'galleries/in-city/:cityname' => redirect{ |p,r| "http://travel-guide.mobi/#{p[:locale]}/cities/travel-to/#{p[:cityname]}" }
    resources :galleries

    # get 'photos/upload', :to => 'photos#upload', :as => :new_photo
    # post 'churn-photos', :to => 'photos#churn_photos', :as => :churn_photos
    match 'photos/driver-for/:gallery_id' => 'photos#driver', :as => :add_photos
    match 'photos/do_upload/:gallery_id/by/:username', :to => 'photos#do_upload', :as => :do_upload
    get 'photos/new_profile_photo', :to => 'photos#new', :defaults => { :is_profile => true }, :as => :new_profile_photo
    get 'photos/new-for-gallery/:gallery_id', :to => 'photos#new', :as => :new_photo_for_gallery
    resources :photos
  
    get '/users', :to => 'users#index', :as => :users
    get '/users/page/:users_page', :to => 'users#index'
    get '/users/show/:username', :to => 'users#show', :as => :user
    put '/users/:id', :to => 'users#update', :as => :update_user
    get '/users/:username/resume', :to => 'users#show', :as => :user_resume
    get '/users/:username/resume/print', :to => 'users#show', :defaults => { :print => true }, :as => :user_resume_print
    get '/users/:username/articles', :to => 'users#reports'
    get '/users/:username/articles/page/:reports_page', :to => 'users#reports'
    get '/users/:username/reports', :to => 'users#reports', :as => :user_reports
    get '/users/:username/reports/show/:name_seo', :to => 'users#report', :as => :user_report
    get '/users/:username/galleries', :to => 'users#galleries', :as => :user_galleries
    get '/users/:username/galleries/page/:galleries_page', :to => 'users#galleries'
    match '/users/scratchpad', :to => 'users#scratchpad', :as => :scratchpad
    get '/users/sign_in', :to => 'users#sign_in', :as => :sign_in
    get '/users/organizer', :to => 'users#organizer', :as => :organizer
    put '/users/show/:id', :to => 'users#update'
    get '/users/new_profile', :to => 'users#new_profile', :as => :new_user_profile
    get '/users/:username/profiles/:profile_id/edit', :to => 'users#edit_profile', :as => :edit_user_profile
    put '/users/:username/profiles/:profile_id', :to => 'users#update_profile', :as => :update_profile
    get '/users/gallery/:galleryname', :to => 'users#gallery', :as => :user_gallery
    get '/users/in-city/:cityname', :to => 'users#index', :as => :users_in_city
    post '/user_profiles', :to => 'users#create_profile'
    match '/users/search', :to => 'users#index', :as => :users_search
    get '/users/:username/github', :to => 'users#github_page', :as => :user_github
    get '/settings', :to => 'users#edit', :as => :settings
    match '/users/new_message', :to => 'users#new_message', :as => :new_message
    # resources :user_profile
    # messages are not a full resource yet.

    get 'tags' => redirect { |params, request| "/#{params[:locale]}/sites/#{request.domain}/tags" }
    get 'tags/:tagname' => redirect { |params, request| "/#{params[:locale]}/tags/view/#{params[:tagname]}" }
    get 'tags/view/:tagname', :to => 'tags#show', :as => :tag

    get 'v', :to => 'utils/utils#version', :as => :version
    get 'sitemap', :to => 'utils/sitemaps#sitemap', :as => :sitemap

    get 'videos', :to => 'videos#index', :as => :videos
    get 'videos/page/:videos_page', :to => 'videos#index'
    get 'videos/show/:youtube_id', :to => 'videos#show', :as => :video
    get 'videos/view/:youtube_id' => redirect { |p,r| "/#{p[:locale]}/videos/show/#{p[:youtube_id]}" }
    post 'videos', :to => 'videos#create'
    get 'videos/new', :to => 'videos#new', :as => :new_video
    get 'videos/in-tag/:tagname' => redirect { |p,r| "/#{p[:locale]}/tags/show/#{p[:tagname]}" }
    # resources :videos

    #
    # redirects
    #
    # cities
    get 'cities/travel-to/:cityname' => redirect { |params, request| "http://travel-guide.mobi/en/cities/travel-to/#{params[:cityname]}" }
    get 'cities' => redirect { |params, request| 'http://travel-guide.mobi/en/cities' }
    get 'cities/*bbb' => redirect { |params, request| "http://travel-guide.mobi/#{params[:locale]}/cities/#{params[:bbb]}" }
    get 'venues/in-city/:cityname' => redirect { |params, request| "http://travel-guide.mobi/en/cities/travel-to/#{params[:cityname]}" }
    #
    # venues
    get 'venues/in-city/:cityname' => redirect { |p,r| "http://travel-guide.mobi/#{p[:locale]}/cities/travel-to/#{p[:cityname]}" }
    get 'venues/show/:venue_name' => redirect { |p, r| "http://travel-guide.mobi/#{p[:locale]}/venues/show/#{p[:venue_name]}" }
    get 'venues/:venue_name/galleries/show/:gallery_name' => redirect { |p,r| "/#{p[:locale]}/galleries/show/#{p[:gallery_name]}/0" }
    # this must be the last line of redirects
    get 'venues/*bbb' => redirect { |p, r| "http://travel-guide.mobi/#{p[:locale]}/venues/#{p[:bbb]}" }
    #
    # other
    match '*other', :to => 'welcome#error500', :as => :error500

  end # scope :locale
  
  get 'search', :to => 'welcome#search'
 
  scope 'spec_runner', :as => :spec_runner do
    root :to => 'spec_runner#all'
    get ':which', :to => 'spec_runner#which', :as => :which
  end

  get 'sitemap_photos', :to => 'utils/sitemaps#photos', :as => :sitemap_photos

  #
  # old legacy stuff
  #
  get 'google4b2e82b4dbbf505d', :to => 'utils/verification#one'
  get 'index.php/events/calendar/*everything' => redirect { |params, request| '/' }
  get 'index.php/events/view/*everything' => redirect { |params, request| '/' }
  get 'index.php/events/in/:cityname' => redirect { |params, request| "/cities/travel-to/#{params[:cityname]}" }
  get 'index.php' => redirect { |params, request| '/' }
  match 'venue_types/*everything' => redirect { |params, request| '/' }
  match 'venue_types' => redirect { |params, request| '/' }
  match 'dictionaryitems/*everything' => redirect { |params, request| '/' }

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  validates :name, :uniqueness => true, :allow_nil => false
  
  field :name_seo, :type => String
  validates :name_seo, :uniqueness => true, :allow_nil => false

  field :descr, :type => String, :default => ''
  
  field :is_public, :type => Boolean, :default => true
  field :is_trash, :type => Boolean, :default => false
  field :is_feature, :type => Boolean, :default => false
  
  field :weight, :type => Integer, :default => 10

  has_many :reports
  has_many :galleries
  has_many :videos

  has_many :children_tags, :class_name => 'Tag', :inverse_of => :parent_tag
  belongs_to :parent_tag, :class_name => 'Tag', :inverse_of => :children_tags

  embeds_many :features
  embeds_many :newsitems

  belongs_to :site

  default_scope where( :is_public => true, :is_trash => false ).order_by( :created_at => :desc )

  before_create do |d|
    if d.name_seo.blank?
      d.name_seo = d.name.to_simple_string
    end
  end

  def self.clear
    if Rails.env.test?
      Tag.each { |r| r.remove }
    end
  end
  
  def self.no_parent
    Tag.where( :parent_tag_id => nil )
  end

  def self.list
    out = Tag.all.order_by( :name => :desc )
    [['', nil]] + out.map { |item| [ item.name, item.id ] }
  end

  # @deprecated, there will be no reports or galleries in tags. There will be only features and newsitems
  def self.n_items
    10
  end
  def self.n_reports
    4
  end
  def self.n_galleries
    4
  end
  def self.n_videos
    4
  end
  
  # @deprecated I don't even know why I have this. Should be simplified into non-being.
  def self.n_features
    4
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  caches_page :index, self::CACHE_OPTIONS
  caches_page :show, self::CACHE_OPTIONS

  def index
    authorize! :index, Tag.new
    # @feature_tags = Tag.features
    @tags = Tag.where( :site_id => @site.id, :parent_tag => nil )
  end

  def show
    @tag = Tag.where( :name_seo => params[:tagname] ).first
    authorize! :show, @tag

    @galleries = @tag.galleries.where( :is_public => true, :is_trash => false ).order_by( :created_at => :desc ).page( params[:galleries_page] )
    @features = []
    @reports = @tag.reports.where( :is_public => true, :is_trash => false ).order_by( :created_at => :desc ).page( params[ :reports_page ] )
    @children_tags = @tag.children_tags
  end

end

app/views/tags/_features.haml
.tags-features
  .title
    %h1
      = link_to t('tags.list'), tags_path

  .items
    - feature_tags.each do |tag|
      .item
        %h3= link_to tag['name_'+@locale.to_s], tag_path(tag.name_seo)

  .c

app/views/tags/_features.html.haml
.tags-features
  .title
    %h1
      = link_to t('tags.list'), tags_path

  .items
    - feature_tags.each do |tag|
      .item
        %h3= link_to tag['name_'+@locale.to_s], tag_path(tag.name_seo)

  .c

app/views/tags/_item.haml
- level ||= 1

%div{ :class => "tag-item tag-item-level-#{level}" }

  %h2{ :class => "level-#{level}" }
    = link_to tag.name, tag_path(tag.name_seo)
    -# = "(#{tag.reports.public.length}) (#{tag.galleries.public.length})"
      
  .descr= tag.descr
  
  - if tag.children_tags.length > 0
    .children-tags-list
      - tag.children_tags.map do |tt|
        = render 'item', :tag => tt, :level => level+1
        
  - if tag.reports.length > 0
    .tag-reports
      - tag.reports[0..Tag.n_reports-1].each do |report|
        = render 'reports/item_mini', :report => report
      .item-mini
        %h5= link_to '[More Reports]', tag_path(tag.name_seo)
      
  - if tag.galleries.length > 0
    %ul.tag-galleries
      - tag.galleries[0..Tag.n_galleries].each do |gallery|
        %li= link_to gallery.name, gallery_path(gallery.galleryname, 0)
      %li ...
      
  - if tag.videos.length > 0
    %ul.tag-videos
      - tag.videos[0..Tag.n_videos].each do |video|
        %li= link_to video.name, video_path(video.youtube_id)
      %li ...

app/views/tags/_item.html.haml
.tag-item

  %h2
    = link_to tag['name_'+@locale.to_s], tag_path(tag.name_seo)
    = "(#{tag.reports.public.length}) (#{tag.galleries.public.length})"

  - if tag.reports.public.length > 0
    %ul.tag-reports
      - tag.reports.public.limit(Tag.n_items).each do |report|
        %li= link_to report.name, report_path(report.name_seo)

  - if tag.galleries.public.length > 0
    %ul.tag-galleries
      - tag.galleries.public.limit(Tag.n_items).each do |gallery|
        %li= link_to gallery.name, gallery_path(gallery.galleryname, 0)

  - if tag.children_tags.length > 0
    .children-tags-list
      - tag.children_tags.map do |tt|
        = render 'item', :tag => tt

app/views/tags/_list.haml
- if tags.length > 0
  .tags--list
    .inner
      .title
        %h3= t('tags.list')
      - tags.each do |tag|
        .item= link_to tag['name_'+@locale.to_s], tag_path(tag.name_seo)

app/views/tags/_list.html.haml
- if tags.length > 0
  .tags--list
    .inner
      .title
        %h3= t('tags.list')
      - tags.each do |tag|
        .item= link_to tag['name_'+@locale.to_s], tag_path(tag.name_seo)

app/views/tags/_list_simple.haml
.list--simple
  %ul.block
    - tags.each do |tag|
      %li= link_to tag.name, tag_path(tag.name_seo)

app/views/tags/index.haml
- content_for :title do
  = t('tags.list')

- if @display_ads && false # hidden
  .center= render 'ads/src/leaderboard'    

.center
  %h1= t('tags.list')
  
.tags-list
  - @tags.each do |tag|
    .item= render 'tags/item', :tag => tag
  - if @tags.blank?
    .item No Tags

- if @display_ads
  .center= render 'ads/src/leaderboard'    

app/views/tags/index.html.haml
- content_for :title do
  = t('tags.list')
  
.title
  %h1= t('tags.list')

= render 'ads/leaderboard_blue'

.feature-tags-list
  - @feature_tags.each do |tag|
    .item= render 'tags/item', :tag => tag

= render 'ads/leaderboard_blue'

.tags-list
  - @tags.each do |tag|
    .item= render 'tags/item', :tag => tag

app/views/tags/show.haml
-## tags/show

- content_for :title do
  = @tag.name
  
.head-1
  .title
    %h1= @tag.name
  -# = render 'features/list', :features => @features[0, Tag.n_features]
  
.col-1
  -# = render 'ads/banner_blue'
  = render 'galleries/list', :galleries => @galleries
  -# = render 'newsitems/list', :newsitems => @newsitems

.col-2
  -# = render 'galleries/list', :galleries => @galleries, :n_thumbs => 4
  - if @features.length > Tag.n_features
    .more-features= render 'features/list', :features => @features[Tag.n_features, 20]

  = render 'reports/list', :reports => @reports, :n_ads => 0
  = render 'tags/list', :tags => @children_tags

  %h4= t('videos.list')
  = render 'videos/list', :videos => @videos

app/views/tags/show.html.haml
-## tags/show

- content_for :title do
  = @tag.name
  
.head-1
  .title
    %h1= @tag['name_'+@locale.to_s]
  = render 'features/list', :features => @features[0, Tag.n_features]
  
.col-1
  = render 'ads/banner_blue'
  = render 'galleries/list', :galleries => @galleries
  = render 'newsitems/list', :newsitems => @newsitems

.col-2
  -# = render 'galleries/list', :galleries => @galleries, :n_thumbs => 4
  - if @features.length > Tag.n_features
    .more-features= render 'features/list', :features => @features[Tag.n_features, 20]
  -# = render 'videos/list', :videos => @videos
  = render 'reports/list', :reports => @reports, :n_ads => 2
  = render 'tags/list', :tags => @children_tags