config/routes.rb
Microsites2::Application.routes.draw do

  root :to => 'welcome#home'

  # then it just disappears...
  # get "/ru/reports/view/Explanation_Of_Symbolic_Links" => redirect { |params, request| "http://piousbox.com/en/users/show/piousbox" }
  
  scope "/:locale", :constraints => { :locale => /en|ru|pt/ } do

    root :to => 'welcome#home'
    get 'about', :to => 'welcome#about', :as => :about
    post 'set_city', :to => 'welcome#set_city', :as => :set_city
    get 'privacy', :to => 'welcome#privacy', :as => :privacy
    get 'contact', :to => 'welcome#contact', :as => :contact
    
    devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :registrations => 'users/registrations'
    }

    get "sites/:domainname.html/newsitems/page/:newsitems_page" => redirect { |params, request|
      "/#{params[:locale]}/sites/#{params[:domainname]}/newsitems/page/#{params[:newsitems_page]}" 
    }, :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    get "sites/:domainname.html", :to => "sites#show", :as => :site,   :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    get 'sites/:domainname/tags', :to => 'tags#index', :as => :tags,   :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    get 'sites/:domainname/tags/page/:tags_page', :to => 'tags#index', :constraints => { :domainname => /.*/, :format => /xml|html|json/ }
    scope 'sites/:domainname',                         :as => :sites,  :constraints => { :domainname => /.*/, :format => /xml|html|json/ } do
      get 'features', :to => 'sites#features', :as => :features
      get 'features/page/:features_page', :to => 'sites#features'
      get 'newsitems/page/:newsitems_page', :to => 'sites#show'
      get 'newspage/:newsitems_page' => redirect { |p,r| "/#{p[:locale]}/sites/#{p[:domainname]}/newsitems/page/#{p[:newsitems_page]}" }

      get 'reports', :to => 'reports#index', :as => :reports
      get 'reports/page/:reports_page', :to => 'reports#index'

      get 'galleries', :to => 'galleries#index', :as => :galleries
      get 'galleries/page/:galleries_page', :to => 'galleries#index'

      get 'sitemap' => redirect { |params, request| "http://#{request.domain}/en/sitemap.xml" }
    end

    get 'reports', :to => 'reports#index', :as => :reports
    get 'reports/page/:reports_page', :to => 'reports#index' # @deprecated, but keep it for Google
    get 'reports/view/:name_seo', :to => 'reports#show', :as => :report
    get 'reports/show/:name_seo', :to => 'reports#show' # @deprecated, I think I'll go with `view` word.
    put 'reports/:id', :to => 'reports#update', :as => :update_report
    get 'reports/:id/edit', :to => 'reports#edit', :as => :edit_report
    get 'reports/new', :to => 'reports#new', :as => :new_report
    post 'reports', :to => 'reports#create'
    resources :reports

    get 'galleries', :to => 'galleries#index', :as => :galleries
    get 'galleries/page/:galleries_page', :to => 'galleries#index' # @deprecated, keep it for Google
    get 'galleries/new', :to => 'galleries#new', :as => :new_gallery
    # @deprecated, instead of `show` there should be `style`
    get 'galleries/show/:galleryname/:photo_idx', :to => 'galleries#show', :as => :gallery, :constraints => { :photo_idx => /.*/ }
    get 'galleries/view/:galleryname' => redirect {|p,r| "/#{p[:locale]}/galleries/show/#{p[:galleryname]}/0" }
    # @deprecated, instead of `show` there should be `style`
    get 'galleries/j_show/:id', :to => 'galleries#j_show', :as => :j_gallery, :defaults => { :format => :json }
    get 'galleries/:style/:galleryname', :to => 'galleries#show', :as => :gallery_show_style, :constraints => { :style => /show_long|show_mini|show/ }
    get 'galleries/:id/edit', :to => 'galleries#edit', :as => :edit_gallery
    post 'galleries/:id', :to => 'galleries#update', :as => :update_gallery
    post 'galleries', :to => 'galleries#create'
    get 'galleries/:galleryname/multiadd', :to => 'photos#multinew', :as => :gallery_multiadd_photos
    post 'galleries/:galleryname/multiadd', :to => 'photos#j_create', :as => :gallery_multiadd_photos, :defaults => { :format => :json }
    get 'galleries/in-city/:cityname' => redirect{ |p,r| "http://travel-guide.mobi/#{p[:locale]}/cities/travel-to/#{p[:cityname]}" }
    resources :galleries

    # get 'photos/upload', :to => 'photos#upload', :as => :new_photo
    # post 'churn-photos', :to => 'photos#churn_photos', :as => :churn_photos
    match 'photos/driver-for/:gallery_id' => 'photos#driver', :as => :add_photos
    match 'photos/do_upload/:gallery_id/by/:username', :to => 'photos#do_upload', :as => :do_upload
    get 'photos/new_profile_photo', :to => 'photos#new', :defaults => { :is_profile => true }, :as => :new_profile_photo
    get 'photos/new-for-gallery/:gallery_id', :to => 'photos#new', :as => :new_photo_for_gallery
    resources :photos
  
    get '/users', :to => 'users#index', :as => :users
    get '/users/page/:users_page', :to => 'users#index'
    get '/users/show/:username', :to => 'users#show', :as => :user
    put '/users/:id', :to => 'users#update', :as => :update_user
    get '/users/:username/resume', :to => 'users#show', :as => :user_resume
    get '/users/:username/resume/print', :to => 'users#show', :defaults => { :print => true }, :as => :user_resume_print
    get '/users/:username/articles', :to => 'users#reports'
    get '/users/:username/articles/page/:reports_page', :to => 'users#reports'
    get '/users/:username/reports', :to => 'users#reports', :as => :user_reports
    get '/users/:username/reports/show/:name_seo', :to => 'users#report', :as => :user_report
    get '/users/:username/galleries', :to => 'users#galleries', :as => :user_galleries
    get '/users/:username/galleries/page/:galleries_page', :to => 'users#galleries'
    match '/users/scratchpad', :to => 'users#scratchpad', :as => :scratchpad
    get '/users/sign_in', :to => 'users#sign_in', :as => :sign_in
    get '/users/organizer', :to => 'users#organizer', :as => :organizer
    put '/users/show/:id', :to => 'users#update'
    get '/users/new_profile', :to => 'users#new_profile', :as => :new_user_profile
    get '/users/:username/profiles/:profile_id/edit', :to => 'users#edit_profile', :as => :edit_user_profile
    put '/users/:username/profiles/:profile_id', :to => 'users#update_profile', :as => :update_profile
    get '/users/gallery/:galleryname', :to => 'users#gallery', :as => :user_gallery
    get '/users/in-city/:cityname', :to => 'users#index', :as => :users_in_city
    post '/user_profiles', :to => 'users#create_profile'
    match '/users/search', :to => 'users#index', :as => :users_search
    get '/users/:username/github', :to => 'users#github_page', :as => :user_github
    get '/settings', :to => 'users#edit', :as => :settings
    match '/users/new_message', :to => 'users#new_message', :as => :new_message
    # resources :user_profile
    # messages are not a full resource yet.

    get 'tags' => redirect { |params, request| "/#{params[:locale]}/sites/#{request.domain}/tags" }
    get 'tags/:tagname' => redirect { |params, request| "/#{params[:locale]}/tags/view/#{params[:tagname]}" }
    get 'tags/view/:tagname', :to => 'tags#show', :as => :tag

    get 'v', :to => 'utils/utils#version', :as => :version
    get 'sitemap', :to => 'utils/sitemaps#sitemap', :as => :sitemap

    get 'videos', :to => 'videos#index', :as => :videos
    get 'videos/page/:videos_page', :to => 'videos#index'
    get 'videos/show/:youtube_id', :to => 'videos#show', :as => :video
    get 'videos/view/:youtube_id' => redirect { |p,r| "/#{p[:locale]}/videos/show/#{p[:youtube_id]}" }
    post 'videos', :to => 'videos#create'
    get 'videos/new', :to => 'videos#new', :as => :new_video
    get 'videos/in-tag/:tagname' => redirect { |p,r| "/#{p[:locale]}/tags/show/#{p[:tagname]}" }
    # resources :videos

    #
    # redirects
    #
    # cities
    get 'cities/travel-to/:cityname' => redirect { |params, request| "http://travel-guide.mobi/en/cities/travel-to/#{params[:cityname]}" }
    get 'cities' => redirect { |params, request| 'http://travel-guide.mobi/en/cities' }
    get 'cities/*bbb' => redirect { |params, request| "http://travel-guide.mobi/#{params[:locale]}/cities/#{params[:bbb]}" }
    get 'venues/in-city/:cityname' => redirect { |params, request| "http://travel-guide.mobi/en/cities/travel-to/#{params[:cityname]}" }
    #
    # venues
    get 'venues/in-city/:cityname' => redirect { |p,r| "http://travel-guide.mobi/#{p[:locale]}/cities/travel-to/#{p[:cityname]}" }
    get 'venues/show/:venue_name' => redirect { |p, r| "http://travel-guide.mobi/#{p[:locale]}/venues/show/#{p[:venue_name]}" }
    get 'venues/:venue_name/galleries/show/:gallery_name' => redirect { |p,r| "/#{p[:locale]}/galleries/show/#{p[:gallery_name]}/0" }
    # this must be the last line of redirects
    get 'venues/*bbb' => redirect { |p, r| "http://travel-guide.mobi/#{p[:locale]}/venues/#{p[:bbb]}" }
    #
    # other
    match '*other', :to => 'welcome#error500', :as => :error500

  end # scope :locale
  
  get 'search', :to => 'welcome#search'
 
  scope 'spec_runner', :as => :spec_runner do
    root :to => 'spec_runner#all'
    get ':which', :to => 'spec_runner#which', :as => :which
  end

  get 'sitemap_photos', :to => 'utils/sitemaps#photos', :as => :sitemap_photos

  #
  # old legacy stuff
  #
  get 'google4b2e82b4dbbf505d', :to => 'utils/verification#one'
  get 'index.php/events/calendar/*everything' => redirect { |params, request| '/' }
  get 'index.php/events/view/*everything' => redirect { |params, request| '/' }
  get 'index.php/events/in/:cityname' => redirect { |params, request| "/cities/travel-to/#{params[:cityname]}" }
  get 'index.php' => redirect { |params, request| '/' }
  match 'venue_types/*everything' => redirect { |params, request| '/' }
  match 'venue_types' => redirect { |params, request| '/' }
  match 'dictionaryitems/*everything' => redirect { |params, request| '/' }

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :load_features, :only => [ :show ]

  caches_page :index, self::CACHE_OPTIONS
  caches_page :not_found, self::CACHE_OPTIONS
  caches_page :show, self::CACHE_OPTIONS

  def new
    @report = Report.new
    authorize! :new, @report
    @tags_list = Tag.all.where( :is_public => true ).list
    @sites_list = Site.all.list
    @cities_list = City.all.list

    respond_to do |format|
      format.html do
        render
      end
      format.json { render :json => @report }
    end
  end

  def create
    @report = Report.new params[:report]
    authorize! :create, @report

    @report.user = @current_user || User.where( :username => 'anon' ).first
    @report.username = @report.user.username
    @report[:lang] = @locale
    @report.name_seo ||= @report.name.to_simple_string
    @report.is_feature = false
    @report.site = @site

    saved = false
    verified = verify_recaptcha( :model => @report, :message => 'There is a problem with recaptcha.' )
    if Rails.env.development?
      verified = true
    end

    if verified
      saved = @report.save
    end

    respond_to do |format|
      if saved

        # photo
        photo = Photo.new 
        photo.photo = params[:report][:photo]
        photo.user = @report.user
        photo.is_public = @report.is_public
        photo.is_trash = false
        photo.report_id = @report.id
        photo.save

        # for homepage
        if @report.is_public
          n = Newsitem.new
          n.report = @report
          n.descr = 'shared a story on'
          n.user = @report.user
          @site.newsitems << n
          if @site.save
            ;
          else
            flash[:error] = flash[:error] + 'City could not be saved (newsitem). '
          end
        end

        expire_page :controller => 'reports', :action => 'index', :domainname => @site.domain
        expire_page :controller => 'sites', :action => 'show', :domainname => @site.domain
        format.html { redirect_to organizer_path, :notice => 'Report was successfully created (but newsitem, no information).' }
        format.json { render :json => @report, :status => :created, :location => @report }
      else
        format.html do
          # puts! @report.errors
          flash[:error] = @report.errors.inspect
          @tags_list = Tag.all.where( :is_public => true ).list
          @sites_list = Site.all.list
          @cities_list = City.all.list

          render :action => "new"
        end
        format.json { render :json => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @report = Report.find(params[:id])
    authorize! :edit, @report

    @tags_list = Tag.all.where( :is_public => true ).list
    @sites_list = Site.all.list
    @cities_list = City.all.list

    respond_to do |f|
      f.html
      f.json
    end
  end
  
  def update
    @report = Report.find(params[:id])
    authorize! :update, @report

    @tags_list = Tag.all.where( :is_public => true ).list
    @sites_list = Site.all.list
    @cities_list = City.all.list

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html do
          redirect_to report_path(@report.name_seo), :notice => 'Report was successfully updated.'
        end
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @report.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def search
    authorize! :search, Report.new
    @reports = Report.where( :name => /#{params[:keyword]}/i )

    if params[:my]
      @reports = @reports.where( :user => current_user)
    end

    @reports = @reports.page( params[:reports_page] )
    
    render :action => :index
  end
  
  def index
    authorize! :index, Report.new
    if params[:domainname].blank?
      redirect_to sites_reports_path( @site.domain )
    else
      @reports = Report.all.where( :site => @site )
      @reports = @reports.page( params[:reports_page] ).per( Report::PER_PAGE )
      respond_to do |format|
        format.html do
          if params[:cityname]
            @features = []
            render :action => :list
          else
            render
          end
        end
        format.json do
          @r = []
          @reports.each do |r|
            unless r.photo.blank?
              r[:photo_url] = r.photo.photo.url(:thumb)
            end
            r.username ||= r.user.username
            r.username ||= ''
            r[:photo_url] ||= ''
            @r.push r
          end
          render :json => @r
        end
      end
    end
  end

  def not_found
    authorize! :not_found, Report.new
  end
  
  def show
    unless params[:name_seo].blank?
      @report = Report.where( :name_seo => params[:name_seo] ).first
    else
      @report = Report.find params[:id]
    end
    
    if @report.blank?
      authorize! :not_found, @report
      render :not_found

    elsif @report.site && ( @report.site != @site )
      authorize! :not_found, @report
      redirect_to "http://#{@report.site.domain}#{report_path(@report.name_seo, :locale => @report.lang)}"

    elsif @report.lang != @locale
      authorize! :not_found, @report
      redirect_to report_path( @report.name_seo, :locale => @report.lang )

    else
      authorize! :show, @report
      respond_to do |format|
        format.html do
          if @report.tag && @report.user.username == @report.tag.name_seo
            # if a characteristic tag
            redirect_to user_report_path(@report.name_seo)
          else
            if @report.tag.blank?
              @recommended = Report.all.where( :is_feature => true ).limit( Feature.n_features )
            else
              @recommended = Report.all.where( :tag => @report.tag, :lang => @locale ).limit( 7 )
              @recommended = @recommended.reject { |r| r.name_seo == @report.name_seo }
            end
            @report_name_seo ||= @report.name_seo
            render
          end
        end
        format.json do
          if @report.photo
            @report[:photo_url] = @report.photo.photo.url(:small)
          else
            @report[:photo_url] = '/assets/missing.png'
          end
          @report.username = @report.user.username
          @report.username ||= ''
          render :json => @report
        end
      end
    end
  end

end

app/views/reports/_features.html.haml
.reports-features
  %h2= t('reports.list')
  .items
    - reports.each do |feature|
      .item
        %h3= link_to feature[:name], report_path( feature.name_seo )
        = render 'meta', :report => feature
        .thumb
          - unless feature.photo.blank?
            = link_to image_tag( feature.photo.photo.url(:thumb) ), report_path( feature.name_seo )
        .subhead= feature[:subhead]
        -# .more= link_to 'Read more...', feature[:link_path]
        .clear
  .clear

app/views/reports/_form.haml
- url ||= reports_path
= form_for @report, :url => url, :html => { :multipart => true } do |f|

  - if @report.errors.any?
    #error_explanation
      %h3= t('e.there_are_errors')

      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  .col-1
    -# .actions.top= f.submit t('g.create')

    .name= f.text_field :name, :class => 'name', :placeholder => t('reports.title')
    .subhead= f.text_area :subhead, :class => 'subhead', :placeholder => t('reports.subtitle')

    .descr= f.text_area :descr, :class => 'tinymce'

  .col-2
    .location
      -#.field
      -#  = f.label :venue_id
      -#  = f.select :venue_ids, options_for_select(@venues_list), {}, { :multiple => true }

      .field
        = f.label :city_id
        = select :report, :city_id, @cities_list

      .field
        %label coords
        = f.text_field :x
        = f.text_field :y
    .c

    .field
      = f.label :tag_id
      = select :report, :tag_id, @tags_list
      
    .field.check
      = f.label :is_public
      = f.check_box :is_public

    .field
      = f.label t('photos.one')
      = f.file_field :photo

    .field
      %hr
      = recaptcha_tags
      
    .actions.bottom
      = f.submit t('g.create')
      
  .c

app/views/reports/_item.haml
.item
  %h2= link_to report.name.titleize, report_path(report.name_seo)
  = render 'meta', :report => report, :idx => idx ||= nil
  - unless report.photo.blank?
    .thumb= link_to image_tag(report.photo.photo.url(:thumb), :alt => ''), report_path(report.name_seo)
  .subhead= report.subhead
  .clear
    
%hr
  

app/views/reports/_list.haml
- n_ads ||= 0

.reports-list
  - reports.each_with_index do |report, idx|
    - if @display_ads
      - if idx > 1 && n_ads > 0
        - if 1 == rand(3)
          - n_ads = n_ads - 1
          = render 'ads/leaderboard'
          %hr

    = render 'reports/item', :report => report, :idx => idx ||= nil

  .c

  = paginate reports, :param_name => :reports_page unless false == @is_paginated

  - if 0 == reports.length
    = t('reports.no_reports')

.c

app/views/reports/_list.html.haml
- n_ads ||= 2

.reports-list
  - reports.each_with_index do |report, idx|
    - if @display_ads
      - if idx > 1 && n_ads > 0
        - if 1 == rand(3)
          - n_ads = n_ads - 1
          = render 'ads/large_rectangle_wrapped'

    = render 'reports/item', :report => report, :idx => idx ||= nil

  .clear

  = paginate reports, :param_name => :reports_page

  - if 0 == reports.length
    = t('reports.none')

  - if 0 == reports.length
    = t('reports.no_reports')

.c

app/views/reports/_main_features.html.haml
.main-feature-reports
  - main_feature_reports.each do |feature|
    .item
      .wrapper
        %h2= link_to feature[:name], report_path( feature.name_seo )
        - unless feature.photo.blank?
          = link_to image_tag( feature.photo.photo.url(:small) ), report_path( feature.name_seo )
        .descr
          = feature[:subhead]
        .more= link_to t('g.read_more'), feature[:link_path]
        .clear
  .clear

app/views/reports/_recommended.html.haml
- if recommended.length > 0
  .reports-recommended
    %h5= t('reports.recommended')

    .items
      .item
        = render 'ads/small_square_gray'
      - recommended.each do |r|
        .item
          .inner
            .thumb
              - unless r.photo.blank?
                = link_to image_tag(r.photo.photo.url(:thumb)), report_path(r.name_seo)
            %h3= link_to r.name, report_path(r.name_seo)

    .c

app/views/reports/edit.haml
%h1= t 'reports.edit'

= render 'form', :url => update_report_path(@report.id)

app/views/reports/edit.html.haml
%h1= t 'reports.edit'

= render 'form', :url => update_report_path(@report.id)

app/views/reports/list.haml
= render 'list', :reports => @reports

app/views/reports/new.haml
%h2= t('reports.new')
= render 'reports/form'

app/views/reports/new.html.haml
%h2= t('reports.new')

= form_for @report, :html => { :multipart => true } do |f|

  - if @report.errors.any?
    #error_explanation
      %h3= t('e.there_are_errors')

      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit t('g.create')

  .row.name= f.text_field :name, :class => 'name', :placeholder => t('reports.title')
  .row.subhead= f.text_area :subhead, :class => 'subhead', :placeholder => t('reports.subtitle')

  .row.descr= f.text_area :descr, :class => 'tinymce'

  .row.check
    = f.label :is_public
    = f.check_box :is_public

  .row
    = f.label :tag_id
    = select :report, :tag, @tags_list

  %h3.addToggle= t('g.add_location')
  .location
    .row
      %label= t('cities.one')
      = select :report, :city, @cities

    .row
      = t('g.coords')
      %br
      = f.text_field :x
      = f.text_field :y

  - if @current_user.blank?
    .row
      .captcha
        %p= t('g.captcha_explanation')
        = recaptcha_tags
      .sign-in
        = link_to t('users.sign_in'), sign_in_path
      .clear

  .actions
    = f.submit t('g.create')

app/views/reports/show.haml
- content_for :title do
  = @report.name
  
.reports-show
  .center= render 'ads/src/leaderboard'

  %h1= @report.name
  = render 'meta', :report => @report
  = render 'ads/links_horizontal_large'
    
  .subhead= @report.subhead

  - unless @report.photo.blank? 
    .float-right= image_tag @report.photo.photo.url(:small)

  .descr
    -# = render 'ads/large_rectangle'
    = raw @report.descr
    = render 'add_this'
    .height-2
      
  .center= render 'ads/src/leaderboard'    
  = render 'application/share_this'
  = render 'application/disqus'

app/views/reports/show.html.haml
- content_for :title do
  = @report.name
  
= content_for :left_menu do
  %ul.menu
    %li= link_to t('g.discussion'), 'javascript:void(0);', :class => :duscussion_link
    %li= link_to t('g.recommended'), 'javascript:void(0);', :class => :recommended_link
    %li.hide= link_to t('g.author'), 'javascript:void(0);'

= content_for :right_menu do
  -#

= content_for :right do
  .a
    -# = render 'ads/links_horizontal_large'
    .center= render 'ads/src/leaderboard'
    = render 'reports/recommended', :recommended => @recommended

= content_for :left do
  .reports-show
    .center= render 'ads/src/leaderboard'
    .height-20

    .span-14.colborder
      %h1= @report.name
      = render 'meta', :report => @report
      -# = render 'ads/links_horizontal_large'
      -# .center= render 'ads/src/leaderboard'
      .suhbead= @report.subhead
      .descr
        -# = render 'ads/large_rectangle'
        = raw @report.descr

    .span-9.last
      - if @report.venues.length > 0
        #reports_show_canvas{ :x => @report.x, :y => @report.y, :name_seo => @report.name_seo }
      - unless @report.photo.blank? 
        = image_tag @report.photo.photo.url(:small)
      - if @report.venues.length > 0
        .reports-show-venues
          %h5= t('venues.list')
          %ul.block
            - @report.venues.each do |venue|
              %li= link_to venue.name, venue_path(venue.name_seo)

      -# = render 'ads/large_rectangle'
      = render 'ads/src/large_rectangle'

    .c